Cg
fitenne/youthcampus-dousheng pull request #15
Opened 2022-06-05 12:58 UTC by successtwodog

完成点赞操作与点赞列表，合并到main

2022-06-05 13:19 UTC, fitenne requested changes

2022-06-05 13:19 UTC, fitenne commented on .vscode/settings.json
> +}
.vscode 不同步

2022-06-05 13:19 UTC, fitenne commented on .gitignore
> +config.yaml
config.yaml 内容不应同步，但是要保留一个模板

2022-06-05 13:19 UTC, fitenne commented on internal/controller/favorite.go
> +	// "fmt"
cleanup，或者省事点就算了🤕，不改直接把这个 Conversation Resolve 掉

2022-06-05 14:11 UTC, successtwodog commented
感谢杨佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月5日(星期天) 晚上9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fitenne/youthcampus-dousheng] Cg (PR #15)





 
@fitenne requested changes on this pull request.
 
 
In .vscode/settings.json:
 &gt; @@ -0,0 +1,3 @@ +{ +    "search.useIgnoreFiles": false +}  
.vscode 不同步
 
 
In .gitignore:
 &gt; \ No newline at end of file +.idea + +config.yaml  
config.yaml 内容不应同步，但是要保留一个模板
 
 
In internal/controller/favorite.go:
 &gt; @@ -1,27 +1,155 @@  package controller    import ( -	"github.com/gin-gonic/gin" +	// "fmt"  
cleanup，或者省事点就算了🤕，不改直接把这个 Conversation Resolve 掉
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-06-05 14:54 UTC, fitenne approved these changes
可吧，能跑

2022-06-06 01:43 UTC, fitenne commented
没时间了，加速吧。。。

2022-06-06 01:43 UTC, merged